platform :ios, '15.0'

target 'FDJ-Excercice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FDJ-Excercice

  pod 'SDWebImageSwiftUI'
  pod 'SwiftGen'

  target 'FDJ-ExcerciceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FDJ-ExcerciceUITests' do
    # Pods for testing
  end

end
